# Generated by Django 3.1.1 on 2020-09-06 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='邮箱验证码')),
                ('email', models.EmailField(max_length=200, verbose_name='验证码邮箱')),
                ('send_type', models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], verbose_name='验证码类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '邮箱验证码信息',
                'verbose_name_plural': '邮箱验证码信息',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_provider', models.BooleanField(default=False, verbose_name='是否可以提供设备')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UpgradeApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_info', models.TextField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'accept'), (2, 'refuse')], verbose_name='申请状态')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': '成为提供者申请',
                'verbose_name_plural': '成为提供者申请',
            },
        ),
        migrations.CreateModel(
            name='OnShelfApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'accept'), (2, 'refuse')], verbose_name='申请状态')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('target_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
            options={
                'verbose_name': '上架申请',
                'verbose_name_plural': '上架申请',
            },
        ),
        migrations.CreateModel(
            name='BorrowApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'accept'), (2, 'refuse')], verbose_name='申请状态')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('target_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
            options={
                'verbose_name': '租借申请',
                'verbose_name_plural': '租借申请',
            },
        ),
    ]
