# Generated by Django 3.1.1 on 2020-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200907_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onshelfapply',
            name='lender',
        ),
        migrations.AlterField(
            model_name='borrowapply',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accept'), (2, 'refuse'), (3, 'outdated')], verbose_name='申请状态'),
        ),
    ]
