# Generated by Django 3.1.1 on 2020-09-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200907_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='borrowapply',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_apply', to='core.user'),
        ),
    ]
