# Generated by Django 3.1.1 on 2020-09-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200907_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowapply',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowapply', to='core.user'),
        ),
    ]
