# Generated by Django 3.1.1 on 2020-09-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200907_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowapply',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apply_set', to='core.user'),
        ),
        migrations.AlterField(
            model_name='borrowapply',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accept'), (2, 'refuse'), (3, 'returned')], verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='borrowapply',
            name='target_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_apply_set', to='core.equipment'),
        ),
    ]
