# Generated by Django 3.1.1 on 2020-09-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200908_2028'),
        ('core', '0006_auto_20200908_1213'),
    ]

    operations = [
    ]
