# Generated by Django 3.1.1 on 2020-09-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200908_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowapply',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='owner_apply_set', to='core.user'),
            preserve_default=False,
        ),
    ]
